### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by nocibambi** [p-e-w/plotinus#29]
When I was going through the installation steps (on Ubuntu 16.04), the `make` command produced a lengthy error message (see below).

I installed all the prerequisites and did not receive any error messages during the preceding steps.

Any hints of the source of the error?

```make
[  4%] Building C object CMakeFiles/dbus_service.dir/src/Service.c.o
/home/andras/plotinus/src/Service.vala: In function ‘__lambda29_’:
/home/andras/plotinus/src/Service.vala:48:9: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         CommandProviderProxy command_provider = Bus.get_proxy.end(result);
         ^
/home/andras/plotinus/src/Service.vala:48:40: warning: passing argument 1 of ‘g_async_initable_new_finish’ from incompatible pointer type [-Wincompatible-pointer-types]
         CommandProviderProxy command_provider = Bus.get_proxy.end(result);
                                        ^
In file included from /usr/include/glib-2.0/gio/gio.h:35:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/andras/plotinus/build/src/Service.c:19:
/usr/include/glib-2.0/gio/gasyncinitable.h:115:10: note: expected ‘GAsyncInitable * {aka struct _GAsyncInitable *}’ but argument is of type ‘PlotinusCommandProviderProxy * {aka struct _PlotinusCommandProviderProxy *}’
 GObject *g_async_initable_new_finish       (GAsyncInitable       *initable,
          ^
/home/andras/plotinus/src/Service.vala:48:9: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         CommandProviderProxy command_provider = Bus.get_proxy.end(result);
         ^
Service.c: In function ‘_dbus_plotinus_service_get_commands’:
Service.c:1011:39: warning: passing argument 1 of ‘plotinus_service_proxy_get_commands’ from incompatible pointer type [-Wincompatible-pointer-types]
/home/andras/plotinus/build/src/Service.c:287:6: note: expected ‘PlotinusServiceProxy * {aka struct _PlotinusServiceProxy *}’ but argument is of type ‘PlotinusService * {aka struct _PlotinusService *}’
 void plotinus_service_proxy_get_commands (PlotinusServiceProxy* self, const char* window_path, gchar** bus_name, char*** command_paths, int* command_p
      ^
Service.c: In function ‘_dbus_plotinus_service_register_window’:
Service.c:1055:42: warning: passing argument 1 of ‘plotinus_service_proxy_register_window’ from incompatible pointer type [-Wincompatible-pointer-types]
/home/andras/plotinus/build/src/Service.c:288:6: note: expected ‘PlotinusServiceProxy * {aka struct _PlotinusServiceProxy *}’ but argument is of type ‘PlotinusService * {aka struct _PlotinusService *}’
 void plotinus_service_proxy_register_window (PlotinusServiceProxy* self, const char* window_path, const gchar* bus_name, const char* command_provider_
      ^
Service.c: In function ‘_dbus_plotinus_service_unregister_window’:
Service.c:1081:44: warning: passing argument 1 of ‘plotinus_service_proxy_unregister_window’ from incompatible pointer type [-Wincompatible-pointer-types]
/home/andras/plotinus/build/src/Service.c:289:6: note: expected ‘PlotinusServiceProxy * {aka struct _PlotinusServiceProxy *}’ but argument is of type ‘PlotinusService * {aka struct _PlotinusService *}’
 void plotinus_service_proxy_unregister_window (PlotinusServiceProxy* self, const char* window_path);
      ^
Service.c: In function ‘_dbus_plotinus_service_show_command_palette’:
Service.c:1196:47: warning: passing argument 1 of ‘plotinus_service_proxy_show_command_palette’ from incompatible pointer type [-Wincompatible-pointer-types]
/home/andras/plotinus/build/src/Service.c:290:6: note: expected ‘PlotinusServiceProxy * {aka struct _PlotinusServiceProxy *}’ but argument is of type ‘PlotinusService * {aka struct _PlotinusService *}’
 void plotinus_service_proxy_show_command_palette (PlotinusServiceProxy* self, PlotinusCommandStruct* commands, int commands_length1, gchar** bus_name,
      ^
Service.c: In function ‘plotinus_service_proxy_proxy_get_commands’:
Service.c:1376:228: error: ‘error’ undeclared (first use in this function)
Service.c:1376:228: note: each undeclared identifier is reported only once for each function it appears in
Service.c: In function ‘plotinus_service_proxy_proxy_register_window’:
Service.c:1428:228: error: ‘error’ undeclared (first use in this function)
Service.c: In function ‘plotinus_service_proxy_proxy_unregister_window’:
Service.c:1451:228: error: ‘error’ undeclared (first use in this function)
Service.c: In function ‘plotinus_service_proxy_proxy_show_command_palette’:
Service.c:1512:228: error: ‘error’ undeclared (first use in this function)
Service.c: In function ‘_dbus_plotinus_command_provider_get_commands’:
Service.c:2170:48: warning: passing argument 1 of ‘plotinus_command_provider_proxy_get_commands’ from incompatible pointer type [-Wincompatible-pointer-types]
/home/andras/plotinus/build/src/Service.c:265:6: note: expected ‘PlotinusCommandProviderProxy * {aka struct _PlotinusCommandProviderProxy *}’ but argument is of type ‘PlotinusCommandProvider * {aka struct _PlotinusCommandProvider *}’
 void plotinus_command_provider_proxy_get_commands (PlotinusCommandProviderProxy* self, gchar** bus_name, char*** command_paths, int* command_paths_len
      ^
Service.c: In function ‘plotinus_command_provider_proxy_proxy_get_commands’:
Service.c:2321:228: error: ‘error’ undeclared (first use in this function)
CMakeFiles/dbus_service.dir/build.make:270: recipe for target 'CMakeFiles/dbus_service.dir/src/Service.c.o' failed
make[2]: *** [CMakeFiles/dbus_service.dir/src/Service.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dbus_service.dir/all' failed
make[1]: *** [CMakeFiles/dbus_service.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by p-e-w** [comment]
This is a Vala compiler bug, as evidenced by the fact that the error occurs in GCC, thus Vala generated invalid C code.

The good news is that the bug has already been fixed in Vala 0.34, so upgrading Vala should resolve the problem. Alternatively, if you are not interested in the D-Bus service, you can just compile from the `v0.2.0` tag which doesn't trigger the bug.

**Comment by avently** [comment]
@p-e-w i have this errors. What can i do? Gtk 3.22.18, Vala 0.26.2, Manjaro

`[  4%] Generating src/Command.c;src/CommandExtractor.c;src/CommandList.c;src/InstanceSettings.c;src/Keybinder.c;src/Module.c;src/PopupWindow.c;src/Service.c;src/Utilities.c
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:82.12-82.45: warning: unhandled error `GLib.RegexError'
    return /_(?!_)/.replace(label, -1, 0, "").strip();
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandExtractor.vala:111.22-111.44: error: The name `get_action_group' does not exist in the context of `Gtk.Window'
        action_map = window.get_action_group(name_parts[0]) as ActionMap;
                     ^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandExtractor.vala:55.20-55.38: error: The name `get_titlebar' does not exist in the context of `Gtk.Window'
    var titlebar = window.get_titlebar() as Gtk.Container;
                   ^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandExtractor.vala:55.9-55.57: error: var declaration not allowed with non-typed initializer
    var titlebar = window.get_titlebar() as Gtk.Container;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandExtractor.vala:56.9-56.16: error: The name `titlebar' does not exist in the context of `Plotinus.CommandExtractor.get_window_commands'
    if (titlebar != null) {
        ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:145.20-145.38: error: The name `get_titlebar' does not exist in the context of `Gtk.Window'
    var titlebar = window.get_titlebar();
                   ^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:145.9-145.40: error: var declaration not allowed with non-typed initializer
    var titlebar = window.get_titlebar();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:146.9-146.16: error: The name `titlebar' does not exist in the context of `Plotinus.Utilities.get_window_title'
    if (titlebar == null)
        ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:149.32-149.39: error: The name `titlebar' does not exist in the context of `Plotinus.Utilities.get_window_title'
    Gtk.HeaderBar header_bar = titlebar as Gtk.HeaderBar;
                               ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:150.31-150.38: error: The name `titlebar' does not exist in the context of `Plotinus.Utilities.get_window_title'
    if (header_bar == null && titlebar is Gtk.Container)
                              ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:150.31-150.38: error: invalid left operand
    if (header_bar == null && titlebar is Gtk.Container)
                              ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:152.32-152.39: error: The name `titlebar' does not exist in the context of `Plotinus.Utilities.get_window_title'
      header_bar = find_widget(titlebar as Gtk.Container, typeof(Gtk.HeaderBar)) as Gtk.HeaderBar;
                               ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandExtractor.vala:58.54-58.61: error: The name `titlebar' does not exist in the context of `Plotinus.CommandExtractor.get_window_commands'
      foreach (var command in get_container_commands(titlebar, {window_title}, true)) {
                                                     ^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Utilities.vala:48.17-48.97: warning: unhandled error `GLib.RegexError'
    var regex = new Regex("(" + string.joinv("|", regex_words) + ")", RegexCompileFlags.CASELESS);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/CommandList.vala:91.19-91.54: warning: unhandled error `GLib.RegexError'
    this.filter = /\s{2,}/.replace(filter, -1, 0, " ").strip().casefold();
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:152.20-152.48: warning: unhandled error `GLib.IOError'
      connection = Bus.get_sync(BusType.SESSION);
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:153.17-153.112: warning: unhandled error `GLib.IOError'
      service = Bus.get_proxy_sync(BusType.SESSION, "com.worldwidemann.plotinus", "/com/worldwidemann/plotinus");
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:92.9-92.57: warning: unhandled error `GLib.IOError'
        connection.register_object(command_path, command);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:165.7-165.73: warning: unhandled error `GLib.IOError'
      connection.register_object(command_provider_path, command_provider);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Module.vala:26.27-26.84: warning: unhandled error `GLib.FileError'
    var executable_path = FileUtils.read_link("/proc/%u/exe".printf(Posix.getpid()));
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:48.49-48.73: warning: unhandled error `GLib.IOError'
        CommandProviderProxy command_provider = Bus.get_proxy.end(result);
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:62.7-62.84: warning: unhandled error `GLib.IOError'
      connection.register_object(command_palette_path, new CommandPalette(commands));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/tmp/yaourt-tmp-me/aur-plotinus-git/src/plotinus/src/Service.vala:18.25-18.106: warning: unhandled error `GLib.IOError'
        (connection) => connection.register_object("/com/worldwidemann/plotinus", new Service(connection)));
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by olejorgenb** [comment]
I'm getting the error using vala 0.34.1 (on NixOS).

    Service.c: In function ‘plotinus_command_provider_proxy_proxy_get_commands’:
    Service.c:2321:228: error: ‘error’ undeclared (first use in this function)
    make[2]: *** [CMakeFiles/gtk_module.dir/build.make:271: CMakeFiles/gtk_module.dir/src/Service.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/gtk_module.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    make[2]: *** [CMakeFiles/dbus_service.dir/build.make:271: CMakeFiles/dbus_service.dir/src/Service.c.o] Error 1
    make[2]: *** Waiting for unfinished jobs....

**Comment by p-e-w** [comment]
@olejorgenb: I can't reproduce this. It works with Vala 0.34 on Ubuntu 16.10. Could you provide more details?

**Comment by olejorgenb** [comment]
Output: https://paste.pound-python.org/show/g1mnR5KFHXcdgugAQCdY/

    $ gcc --version
    gcc (GCC) 6.4.0

But if it works for you it's probably some weird combination of how NixOS does things and vala. Couldn't find any similar issues searching https://github.com/NixOS/nixpkgs/issues
